version: '3'

services:
  rakemovie-db:
    image: bitnami/postgresql:15.1.0
    ports:
      - 127.0.0.1:${POSTGRESQL_PORT}:5432
    volumes:
      - rakemovie-db-volume:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    restart: unless-stopped

volumes:
  rakemovie-db-volume: